# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      LILYPOND_FILES: "*.ly"
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - uses: codello/setup-lilypond@v0.1.0
      with:
        lilypond-version: 2.24
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run
      run: sbt run
    - name: Get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(find ${{github.workspace}} -name "${{ env.LILYPOND_FILES }}" -printf "%P\n" | xargs)"
    - name: LILYPOND files considered echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: Setup LilyPond
      run: |
        lilypond -fpdf ${{ steps.getfile.outputs.files }}
    - name: Configure Git
      run: |
        mv *.midi output/midi
        mv *.pdf output/pdf
        git config --global user.email "sflor5@alumno.uned.es"
        git config --global user.name "balath"
        git add .
        git commit -m "Add output files"
        git push