# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      LILYPOND_FILES: "*.ly"

    steps:
    - uses: actions/checkout@v3
    - uses: codello/setup-lilypond@v0.1.0
      with:
        lilypond-version: 2.24
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run
      run: sbt run
    - name: Get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(find ${{github.workspace}} -name "${{ env.LILYPOND_FILES }}" -printf "%P\n" | xargs)"
    - name: LILYPOND files considered echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: Setup LilyPond
      run: lilypond -V -fpdf -fmidi ${{ steps.getfile.outputs.files }}
    - name: Configure Git
      run: |
        git config --global user.email "sflor5@alumno.uned.es"
        git config --global user.name "balath"
        git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.GH_TOKEN }} | base64)"
    - name: Add files
      run: git add .
    - name: Commit changes
      run: git commit -m "Add action files"
    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}